// lib/firebase_options.dart
// TODO: Replace this file with the real firebase_options.dart generated by:
//   flutterfire configure
// After setting up your Firebase project at https://console.firebase.google.com

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported.');
      default:
        throw UnsupportedError('Unknown platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXs86zLeuBqZZR4-eC-fueMO37YTr7XU',
    appId: '1:879216565551:web:6a5e72e9bb17d3a52015da',
    messagingSenderId: '879216565551',
    projectId: 'aagte-classes',
    authDomain: 'aagte-classes.firebaseapp.com',
    storageBucket: 'aagte-classes.firebasestorage.app',
    measurementId: 'G-4P1MNCRLLQ',
  );

  // !! REPLACE ALL VALUES BELOW WITH YOUR ACTUAL FIREBASE CONFIG !!

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmQXANbV-yqRYymPD82xu4fx2H8MBdWS8',
    appId: '1:879216565551:android:f42743d2118bc0142015da',
    messagingSenderId: '879216565551',
    projectId: 'aagte-classes',
    storageBucket: 'aagte-classes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKbc-YoKC5heDmBzAjuj58eVphBScCL4',
    appId: '1:879216565551:ios:29f891267d40200b2015da',
    messagingSenderId: '879216565551',
    projectId: 'aagte-classes',
    storageBucket: 'aagte-classes.firebasestorage.app',
    iosBundleId: 'com.example.aagteClasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpKbc-YoKC5heDmBzAjuj58eVphBScCL4',
    appId: '1:879216565551:ios:29f891267d40200b2015da',
    messagingSenderId: '879216565551',
    projectId: 'aagte-classes',
    storageBucket: 'aagte-classes.firebasestorage.app',
    iosBundleId: 'com.example.aagteClasses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnXs86zLeuBqZZR4-eC-fueMO37YTr7XU',
    appId: '1:879216565551:web:8008b4039f050aa42015da',
    messagingSenderId: '879216565551',
    projectId: 'aagte-classes',
    authDomain: 'aagte-classes.firebaseapp.com',
    storageBucket: 'aagte-classes.firebasestorage.app',
    measurementId: 'G-NE8MQKX4MZ',
  );

}